### ISSUE TITLE
Destructive PyPi Deploys

### ISSUE THREAD

**Issue by gwenwahl** [QuiNovas/sqs-extended-client#11]
Hey just a heads up that right now any new versions delete the older ones from PyPi, which can make it hard when you try to keep your versions pinned and such.

**Comment by joseph-wortmann** [comment]
@gwenwahl 

Sorry. My bad. I often do that when previous versions have something broken in them (if they are alpha/beta) but I will cease at least on this project to prevent future headaches for you.

**Comment by gwenwahl** [comment]
No worries thanks!
